# (name, series, bey_type, face_bolt, energy_ring, fusion_wheel, spin_track, performance_tip)
BEYBLADES = [
    # ── METAL FUSION ─────────────────────────────────────────────────────────
    ("Storm Pegasus 105RF",       "Metal Fusion", "Attack",
     "Pegasus",      "Pegasus I",      "Storm",         "105",              "RF"),
    ("Lightning L-Drago 100HF",   "Metal Fusion", "Attack",
     "L-Drago",      "L-Drago I",      "Lightning",     "100",              "HF"),
    ("Rock Leone 145WB",          "Metal Fusion", "Defense",
     "Leone",        "Leone",          "Rock",          "145",              "WB"),
    ("Dark Bull H145SD",          "Metal Fusion", "Stamina",
     "Bull",         "Bull",           "Dark",          "H145",             "SD"),
    ("Flame Sagittario C145S",    "Metal Fusion", "Stamina",
     "Sagittario",   "Sagittario I",   "Flame",         "C145",             "S"),
    ("Cyber Pegasus 105F",        "Metal Fusion", "Attack",
     "Pegasus",      "Pegasus I",      "Cyber",         "105",              "F"),
    ("Poison Serpent SW145SD",    "Metal Fusion", "Stamina",
     "Serpent",      "Serpent",        "Poison",        "SW145",            "SD"),
    ("Rock Aries ED145B",         "Metal Fusion", "Defense",
     "Aries",        "Aries",          "Rock",          "ED145",            "B"),
    ("Burn Fireblaze 135MS",      "Metal Fusion", "Stamina",
     "Fireblaze",    "Fireblaze",      "Burn",          "135",              "MS"),
    ("Storm Aquario 100HF/S",     "Metal Fusion", "Attack",
     "Aquario",      "Aquario",        "Storm",         "100",              "HF/S"),
    ("Rock Orso D125B",           "Metal Fusion", "Defense",
     "Orso",         "Orso",           "Rock",          "D125",             "B"),
    ("Counter Leone D125B",       "Metal Fusion", "Defense",
     "Leone",        "Leone",          "Counter",       "D125",             "B"),
    ("Thermal Pisces T125ES",     "Metal Fusion", "Stamina",
     "Pisces",       "Pisces",         "Thermal",       "T125",             "ES"),
    ("Earth Eagle 145WD",         "Metal Fusion", "Stamina",
     "Eagle",        "Eagle",          "Earth",         "145",              "WD"),
    ("Flame Libra T125ES",        "Metal Fusion", "Stamina",
     "Libra",        "Libra",          "Flame",         "T125",             "ES"),
    ("Evil Gemios DF145FS",       "Metal Fusion", "Balance",
     "Gemios",       "Gemios",         "Evil",          "DF145",            "FS"),
    ("Rock Scorpio T125JB",       "Metal Fusion", "Defense",
     "Scorpio",      "Scorpio",        "Rock",          "T125",             "JB"),
    ("Flame Cancer CH120SF",      "Metal Fusion", "Balance",
     "Cancer",       "Cancer",         "Flame",         "CH120",            "SF"),
    ("Storm Capricorn M145Q",     "Metal Fusion", "Attack",
     "Capricorn",    "Capricorn",      "Storm",         "M145",             "Q"),
    ("Rock Giraffe R145WB",       "Metal Fusion", "Defense",
     "Giraffe",      "Giraffe",        "Rock",          "R145",             "WB"),
    ("Vulcan Horuseus 145D",      "Metal Fusion", "Balance",
     "Horuseus",     "Horuseus",       "Vulcan",        "145",              "D"),
    ("Twisted Tempo 145WD",       "Metal Fusion", "Defense",
     "Tempo",        "Tempo",          "Twisted",       "145",              "WD"),
    ("Quetzalcoatl 90WF",         "Metal Fusion", "Attack",
     "Quetzalcoatl", "Quetzalcoatl",   "Quetzalcoatl",  "90",               "WF"),
    ("Gravity Perseus AD145WD",   "Metal Fusion", "Balance",
     "Perseus",      "Perseus",        "Gravity",       "AD145",            "WD"),
    ("Burn Phoenix 135MS",        "Metal Fusion", "Stamina",
     "Phoenix",      "Phoenix",        "Burn",          "135",              "MS"),
    ("Rock Escolpio T125JB",      "Metal Fusion", "Defense",
     "Escolpio",     "Escolpio",       "Rock",          "T125",             "JB"),

    # ── METAL MASTERS ────────────────────────────────────────────────────────
    ("Galaxy Pegasus W105R²F",    "Metal Masters", "Attack",
     "Pegasus",      "Pegasus II",     "Galaxy",        "W105",             "R²F"),
    ("Meteo L-Drago LW105LF",     "Metal Masters", "Attack",
     "L-Drago",      "L-Drago II",     "Meteo",         "LW105",            "LF"),
    ("Ray Unicorno D125CS",       "Metal Masters", "Balance",
     "Unicorno",     "Unicorno I",     "Ray",           "D125",             "CS"),
    ("Fang Leone 130W²D",         "Metal Masters", "Defense",
     "Leone",        "Leone",          "Fang",          "130",              "W²D"),
    ("Flame Byxis 230WD",         "Metal Masters", "Stamina",
     "Byxis",        "Byxis",          "Flame",         "230",              "WD"),
    ("Screw Capricorne 90MF",     "Metal Masters", "Attack",
     "Capricorne",   "Capricorne",     "Screw",         "90",               "MF"),
    ("Sol Blaze V145AS",          "Metal Masters", "Stamina",
     "Blaze",        "Blaze",          "Sol",           "V145",             "AS"),
    ("Ray Gil 100RSF",            "Metal Masters", "Attack",
     "Gil",          "Gil",            "Ray",           "100",              "RSF"),
    ("Earth Virgo GB145BS",       "Metal Masters", "Stamina",
     "Virgo",        "Virgo",          "Earth",         "GB145",            "BS"),
    ("Mad Gasher CH120FS",        "Metal Masters", "Attack",
     "Gasher",       "Gasher",         "Mad",           "CH120",            "FS"),
    ("Beat Lynx TH170WD",         "Metal Masters", "Balance",
     "Lynx",         "Lynx",           "Beat",          "TH170",            "WD"),
    ("Gravity Destroyer AD145WD", "Metal Masters", "Balance",
     "Perseus",      "Perseus",        "Gravity",       "AD145",            "WD"),
    ("Thermal Lacerta WA130HF",   "Metal Masters", "Attack",
     "Lacerta",      "Lacerta",        "Thermal",       "WA130",            "HF"),
    ("Evil Befall UW145EWD",      "Metal Masters", "Stamina",
     "Befall",       "Befall",         "Evil",          "UW145",            "EWD"),
    ("Nightmare Rex SW145SD",     "Metal Masters", "Stamina",
     "Rex",          "Rex",            "Nightmare",     "SW145",            "SD"),
    ("Poison Zurafa S130MB",      "Metal Masters", "Stamina",
     "Zurafa",       "Zurafa",         "Poison",        "S130",             "MB"),
    ("Rock Zurafa R145WB",        "Metal Masters", "Defense",
     "Zurafa",       "Zurafa",         "Rock",          "R145",             "WB"),
    ("Dark Poseidon 145WD",       "Metal Masters", "Stamina",
     "Poseidon",     "Poseidon",       "Dark",          "145",              "WD"),
    ("Counter Scorpio T125D",     "Metal Masters", "Balance",
     "Scorpio",      "Scorpio",        "Counter",       "T125",             "D"),
    # 4D beyblades that debuted in Metal Masters
    ("Big Bang Pegasus F:D",      "Metal Masters", "Attack",
     "Pegasus",      "Pegasus III",    "Big Bang",      "F:D (4D Bottom)",  "F:D"),
    ("Variares D:D",              "Metal Masters", "Attack",
     "Aries",        "Aries II",       "Variares",      "D:D (4D Bottom)",  "D:D"),
    ("Blitz Unicorno 100RSF",     "Metal Masters", "Attack",
     "Unicorno",     "Unicorno II",    "Blitz",         "100",              "RSF"),
    ("Hades Kerbecs BD145DS",     "Metal Masters", "Stamina",
     "Kerbecs",      "Kerbecs",        "Hades",         "BD145",            "DS"),
    ("Flash Sagittario 230WD",    "Metal Masters", "Stamina",
     "Sagittario",   "Sagittario II",  "Flash",         "230",              "WD"),

    # ── METAL FURY (4D System) ───────────────────────────────────────────────
    ("L-Drago Destructor F:S",    "Metal Fury", "Attack",
     "L-Drago",      "L-Drago III",    "L-Drago Destructor", "F:S (4D Bottom)", "F:S"),
    ("Phantom Orion B:D",         "Metal Fury", "Stamina",
     "Orion",        "Orion",          "Phantom",       "B:D (4D Bottom)",  "B:D"),
    ("Jade Jupiter S130RB",       "Metal Fury", "Defense",
     "Jupiter",      "Jupiter",        "Jade",          "S130",             "RB"),
    ("Kreis Cygnus 145WD",        "Metal Fury", "Stamina",
     "Cygnus",       "Cygnus",         "Kreis",         "145",              "WD"),
    ("Diablo Nemesis X:D",        "Metal Fury", "Balance",
     "Nemesis",      "Nemesis",        "Diablo",        "X:D (4D Bottom)",  "X:D"),
    ("Duo Uranus 230WD",          "Metal Fury", "Stamina",
     "Uranus",       "Uranus",         "Duo",           "230",              "WD"),
    ("Spiral Lyre ED145MF",       "Metal Fury", "Balance",
     "Lyre",         "Lyre",           "Spiral",        "ED145",            "MF"),
    ("Death Quetzalcoatl 125RDF", "Metal Fury", "Stamina",
     "Quetzalcoatl", "Quetzalcoatl II","Death",         "125",              "RDF"),
    ("Omega Dragonis 85XF",       "Metal Fury", "Attack",
     "Dragonis",     "Dragonis",       "Omega",         "85",               "XF"),
    ("Scythe Kronos T125EDS",     "Metal Fury", "Stamina",
     "Kronos",       "Kronos",         "Scythe",        "T125",             "EDS"),
    ("Ronin Dragoon LW160BSF",    "Metal Fury", "Balance",
     "Dragoon",      "Dragoon",        "Ronin",         "LW160",            "BSF"),
    ("Dark Knight Dragooon LW160B","Metal Fury", "Attack",
     "Dragooon",     "Dragooon",       "Dark Knight",   "LW160",            "B"),
    ("Grand Cetus T125RS",        "Metal Fury", "Defense",
     "Cetus",        "Cetus",          "Grand",         "T125",             "RS"),
    ("Fafnir Knight A:D",         "Metal Fury", "Balance",
     "Knight",       "Knight",         "Fafnir",        "A:D (4D Bottom)",  "A:D"),
    ("Gladiator Bahamdia SP230GF","Metal Fury", "Defense",
     "Bahamdia",     "Bahamdia",       "Gladiator",     "SP230",            "GF"),
    ("Prototype Nemesis",         "Metal Fury", "Balance",
     "Nemesis",      "Nemesis",        "Prototype",     "AD145",            "D"),
    ("Cosmic Pegasus F:D",        "Metal Fury", "Attack",
     "Pegasus",      "Pegasus IV",     "Cosmic",        "F:D (4D Bottom)",  "F:D"),
    ("Samurai Ifraid W145CF",     "Metal Fury", "Attack",
     "Ifraid",       "Ifraid",         "Samurai",       "W145",             "CF"),
    ("Hades Ad145SWD",            "Metal Fury", "Defense",
     "Hades",        "Hades",          "Hades",         "Ad145",            "SWD"),
    ("Screw Fox R145MF",          "Metal Fury", "Attack",
     "Fox",          "Fox",            "Screw",         "R145",             "MF"),
]
